{% set name = "xscen" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xscen-{{ version }}.tar.gz
  sha256: 50aeda7ef1788fc15ca95aa657e82902a7a489c2e8d11f948e79f576e8c99b2d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - babel
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python >=3.9
    # Main package
    - babel
    - cartopy
    - cftime
    - cf_xarray >=0.7.6
    - clisops >=0.10.0
    - dask-core
    - flox
    - fsspec
    - geopandas
    - h5netcdf
    - h5py
    - intake-esm >=2023.07.07
    - matplotlib-base
    - netCDF4
    - numcodecs
    - numpy
    - pandas >=2.2
    - parse
    - pyyaml
    - rechunker
    - scipy
    - shapely >=2.0
    - sparse
    - toolz
    - xarray >=2023.11.0
    - xclim >=0.48.2
    - xesmf >=0.7
    - zarr
    # Opt
    - nc-time-axis >=1.3.1
    - pyarrow >=10.0.1  # Used when opening catalogs

test:
  imports:
    - xscen
  source_files:
    - docs
    - tests
  commands:
    - pip check
    - pytest tests -m "not requires_netcdf"
  requires:
    - pip
    - pytest
    - xdoctest

about:
  home: https://github.com/Ouranosinc/xscen
  summary: A climate change scenario-building analysis framework, built with xclim/xarray.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aulemahal
    - juliettelavoie
    - RondeauG
    - Zeitsperre
